softdepend: [Factions, LuckPerms, Vault, PlaceholderAPI]
depend: [RecraftedCore]
permissions:
  chatplugin.spy:
    description: let you see all chats without range restrictions using /spy
    default: false
  chatplugin.color:
    description: Translate color codes in the message
    default: false
  chatplugin.papi:
    description: Use Placeholders from placholder api in your message
    default: false

commands:
  spy:
    description: Spy on all channels without range restriction
    usage: /spy
    permission: chatplugin.spy
    permission-message: Fuck of you are not allowed to spy on people

  mutech:
    description: Mute one or more given channels
    usage: /mute <channel> <names>

  unmutech:
    description: Unmute a given channel
    usage: /unmute <channel> <names>

  list_channels:
    description: List all available channels
    usage: /list_channels
